name: project_commit
channels:
- defaults
dependencies:
- pip=9.0.1
- python
- sqlite
- wheel
- pip:
  - click==6.7
  - flask==0.12.2
  - flask-sqlalchemy==2.3.2
  - itsdangerous==0.24
  - jinja2==2.10
  - markupsafe==1.0
  - sqlalchemy==1.1.15
  - werkzeug==0.12.2

