name: project_commit
channels:
- defaults
dependencies:
- pip=9.0.1
- python=3.6.3
- setuptools=36.5.0
- sqlite=3.20.1
- wheel=0.30.0
- xz=5.2.3
- zlib=1.2.11
- pip:
  - click==6.7
  - flask==0.12.2
  - flask-sqlalchemy==2.3.2
  - itsdangerous==0.24
  - jinja2==2.10
  - markupsafe==1.0
  - sqlalchemy==1.1.15
  - werkzeug==0.12.2

